// import './components/events.js'
// import './components/arrays.js'
// import './components/source.js'
// import './components/promise.js'
// import './components/interval.js'
// import './components/map.js'
import './components/merge.js'